import { LoginManager, AccessToken, Settings } from 'react-native-fbsdk-next'
import Constants from 'expo-constants'

let isConfigured = false

/**
 * Initialize the Facebook SDK. Call this once when the app starts.
 *
 * The App ID and Client Token are read from app.json expo.extra.
 * On iOS the same values also come from Info.plist (auto-generated by
 * the react-native-fbsdk-next plugin during prebuild).
 *
 * NOTE: unlike Google, Facebook uses two separate identifiers:
 *   - facebookAppId    — public, used for OAuth
 *   - facebookClientToken — semi-public, needed for the native SDK to
 *     make Graph API calls without a user access token
 */
export function configureFacebookSignIn() {
  if (isConfigured) return

  const appId = Constants.expoConfig?.extra?.facebookAppId
  const clientToken = Constants.expoConfig?.extra?.facebookClientToken

  if (!appId) {
    console.warn('Facebook Sign-In: facebookAppId not configured in app.json extra')
    return
  }

  Settings.setAppID(String(appId))
  if (clientToken) Settings.setClientToken(String(clientToken))

  // Required by iOS 14+ tracking transparency. We do not use FB Ads/Events,
  // so we opt out of the ad-tracking prompt.
  Settings.initializeSDK()

  isConfigured = true
}

export interface FacebookSignInResult {
  accessToken: string
  userId: string
}

/**
 * Trigger the Facebook Sign-In flow.
 * Returns the access token, or null if the user cancels.
 *
 * Only requests the minimum scopes: `email` and `public_profile`.
 * These do NOT require App Review — anyone with a Facebook account can use
 * them the moment the app is created. Anything richer (friends, posts,
 * pages) does require App Review from Meta.
 */
export async function signInWithFacebook(): Promise<FacebookSignInResult | null> {
  configureFacebookSignIn()

  const result = await LoginManager.logInWithPermissions(['email', 'public_profile'])

  if (result.isCancelled) return null

  const tokenData = await AccessToken.getCurrentAccessToken()
  if (!tokenData?.accessToken) {
    throw new Error('Δεν λάβαμε access token από το Facebook')
  }

  return {
    accessToken: tokenData.accessToken,
    userId: tokenData.userID,
  }
}

/**
 * Sign out from Facebook (revokes the local session).
 */
export async function signOutFacebook() {
  try {
    configureFacebookSignIn()
    LoginManager.logOut()
  } catch (err) {
    console.warn('Facebook sign-out error:', err)
  }
}
